version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - run: npm run style
      - run: npm run lint

      - run: npm run build:prod
      - run: npm run test:coverage -- --watch=false
      - run: npm run e2e

      - run:
      - run:
          name: Tar & Gzip compiled app
          name: Move compiled app to workspace
          command: tar zcf dist.tar.gz dist/lemon-mart

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace/dist
            mv dist/lemon-mart /tmp/workspace/dist/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/lemon-mart
  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npx vercel --token $VERCEL_TOKEN --platform-version 2
          --prod /tmp/workspace/dist/lemon-mart --confirm
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
